project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!README.md"

website:
  title: "ineAtlas.data"
  favicon: icon/favicon.ico
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Documentation"
        menu:
          - text: "Income"
            file: documentation/income.qmd
          - text: "Income sources"
            file: documentation/income_sources.qmd
          - text: "Demographics"
            file: documentation/demographics.qmd
          - text: "Distribution by sex"
            file: documentation/distribution_sex.qmd
          - text: "Distribution by sex and age"
            file: documentation/distribution_sex_age.qmd
          - text: "Distribution by sex and nationality"
            file: documentation/distribution_sex_nationality.qmd
          - text: "Inequality indicators"
            file: documentation/gini_p80p20.qmd
          - text: "Census tract geometries"
            file: documentation/geometries.qmd
    right:
      - icon: github
        href: https://github.com/pablogguz/ineAtlas.data
  sidebar:
    style: "docked"
    search: true

format:
  html:
    theme: 
      - cosmo
      - styles.scss   
    toc: true
    head: |
      <link rel="apple-touch-icon" sizes="180x180" href="icon/apple-touch-icon.png">
      <link rel="icon" type="image/png" sizes="32x32" href="icon/favicon-32x32.png">
      <link rel="icon" type="image/png" sizes="16x16" href="icon/favicon-16x16.png">
      <link rel="manifest" href="icon/site.webmanifest">