project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!README.md"

website:
  title: "ineAtlas.data"
  favicon: icon/favicon.ico
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Documentation"
        menu:
          - text: "Income"
            file: documentation/income.qmd
          - text: "Income sources"
            file: documentation/income_sources.qmd
          - text: "Demographics"
            file: documentation/demographics.qmd
          - text: "Distribution by sex"
            file: documentation/distribution_sex.qmd
          - text: "Distribution by sex and age"
            file: documentation/distribution_sex_age.qmd
          - text: "Distribution by sex and nationality"
            file: documentation/distribution_sex_nationality.qmd
          - text: "Inequality indicators"
            file: documentation/gini_p80p20.qmd
          - text: "Census tract geometries"
            file: documentation/geometries.qmd
    right:
      - icon: github
        href: https://github.com/pablogguz/ineAtlas.data
  sidebar:
    style: "docked"
    search: true

format:
  html:
    include-in-header:
      text: |
        <!-- Primary Meta Tags -->
        <title>ineAtlas.data - Granular socioeconomic indicators for Spain</title>
        <meta name="title" content="ineAtlas.data - Granular socioeconomic indicators for Spain">
        <meta name="description" content="Data repository containing processed socioeconomic indicators from the Spanish Statistical Office (INE) at municipality, district, and census tract level.">

        <!-- Open Graph / Facebook -->
        <meta property="og:type" content="website">
        <meta property="og:url" content="https://pablogguz.github.io/ineAtlas.data/">
        <meta property="og:title" content="ineAtlas.data - Granular socioeconomic indicators for Spain">
        <meta property="og:description" content="Data repository containing processed socioeconomic indicators from the Spanish Statistical Office (INE) at municipality, district, and census tract level.">
        <meta property="og:image" content="https://pablogguz.github.io/ineAtlas.data/icon/logo_data.png">

        <!-- Twitter -->
        <meta name="twitter:card" content="summary_large_image">
        <meta name="twitter:url" content="https://pablogguz.github.io/ineAtlas.data/">
        <meta name="twitter:title" content="ineAtlas.data - Granular socioeconomic indicators for Spain">
        <meta name="twitter:description" content="Data repository containing processed socioeconomic indicators from the Spanish Statistical Office (INE) at municipality, district, and census tract level.">
        <meta name="twitter:image" content="https://pablogguz.github.io/ineAtlas.data/icon/logo_data.png">
    theme: 
      - cosmo
      - styles.scss   
    toc: true
    head: |
      <link rel="apple-touch-icon" sizes="180x180" href="icon/apple-touch-icon.png">
      <link rel="icon" type="image/png" sizes="32x32" href="icon/favicon-32x32.png">
      <link rel="icon" type="image/png" sizes="16x16" href="icon/favicon-16x16.png">
      <link rel="manifest" href="icon/site.webmanifest">